version: "3.9"

services:
  react:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["/start.sh"]
